/-!
# BG3Rules.lean — Formalized Game-Rule Axioms

This file contains axioms encoding specific BG3 spell and mechanic
rules, translated from bg3.wiki data.  These are the **research
targets** for the VALOR framework.

## Research Problems (Top-Venue Candidates)

### P1: Damage Source / Rider / DRS Composition Soundness
The three-tier damage system (DS, DR, DRS) can cause damage riders to
apply *recursively* when a DRS effect is present.  We axiomatize the
composition rules and search for states where total damage exceeds
any reasonable bound.

### P2: Reaction Chain Termination
Reactions (Counterspell, Hellish Rebuke, Armour of Agathys) can
trigger further reactions.  We prove the chain must terminate.

### P3: Concentration Invariant
At most one concentration spell per entity at any time.

### P4: Action Economy Boundedness
Haste + Action Surge + Extra Attack: is the total number of attacks
per turn bounded?

### P5: Status Effect Stack Consistency
Stack ID / StackType must preserve uniqueness invariants.

These are auto-generated by `llm_to_lean.py` in production; below
are hand-crafted seed axioms for the five research problems.
-/

import Core.Types
import Core.Engine

namespace VALOR.Rules

open VALOR

-- ═══════════════════════════════════════════════════════════════════════
-- P1: DAMAGE SOURCE / RIDER / DRS COMPOSITION
-- ═══════════════════════════════════════════════════════════════════════

/--
A DamageSource is a direct damage effect (weapon attack, spell hit).
A DamageRider is bonus damage that "rides" on a source (Hex, coatings).
A DRS is a rider that is *treated as* a source, causing riders to
reapply—this is the root cause of extreme damage stacking.
-/
inductive DamageLayer where
  | source : DamageRoll → DamageLayer
  | rider  : DamageRoll → DamageLayer
  | drs    : DamageRoll → DamageLayer  -- rider treated as source
  deriving Repr

/--
Compute total damage from a mixed set of layers.
Riders apply once per source; DRS effects each create an additional
"virtual source" that also attracts riders.
-/
def computeTotalDamage (layers : List DamageLayer) (targetRes : DamageType → DamageRelation) : Int :=
  let sources := layers.filterMap fun | .source r => some r | .drs r => some r | _ => none
  let riders  := layers.filterMap fun | .rider r  => some r | _ => none
  sources.foldl (fun acc src =>
    let srcDmg := applyDamageRelation src.dice.maxVal (targetRes src.dmgType)
    let riderDmg := riders.foldl (fun a r =>
      a + applyDamageRelation r.dice.maxVal (targetRes r.dmgType)
    ) 0
    acc + srcDmg + riderDmg
  ) 0

/--
**Research Claim P1**: With N DRS effects and M riders, total damage
scales as O((N+1) × M) — i.e., linear in DRS count × rider count.
A single attack with k DRS effects causes riders to apply (k+1) times.
This is the formal basis for the "thousands of damage" exploits.
-/
theorem drs_damage_scaling (baseDmg : Int) (riderDmg : Int) (n_drs : Nat) :
    (n_drs + 1) * riderDmg + baseDmg = baseDmg + riderDmg * (n_drs + 1) := by
  omega

-- ═══════════════════════════════════════════════════════════════════════
-- P2: REACTION CHAIN TERMINATION
-- ═══════════════════════════════════════════════════════════════════════

/--
Model a chain of reactions.  Each entity has ≤1 reaction per round.
With N entities, the maximum chain length is N (each reacts at most once).
-/
structure ReactionChainState where
  entities       : List EntityId
  reactionsUsed  : List EntityId  -- entities that already reacted

def ReactionChainState.canReact (s : ReactionChainState) (e : EntityId) : Bool :=
  s.entities.contains e && !(s.reactionsUsed.contains e)

def ReactionChainState.useReaction (s : ReactionChainState) (e : EntityId) : ReactionChainState :=
  { s with reactionsUsed := e :: s.reactionsUsed }

/--
The reaction chain length is bounded by the number of entities.
This is the termination measure: `entities.length - reactionsUsed.length`
strictly decreases on each reaction.
-/
theorem reaction_chain_bounded (s : ReactionChainState) (e : EntityId)
    (h_can : s.canReact e = true) :
    s.useReaction e |>.reactionsUsed.length > s.reactionsUsed.length := by
  simp [ReactionChainState.useReaction]
  omega

/--
**Hellish Rebuke axiom**: When entity A damages entity B, and B has
Hellish Rebuke prepared and an unused reaction, B may react with
2d10 Fire damage to A.  This consumes B's reaction.

Key: if A has Armour of Agathys and Hellish Rebuke, it could
counter-react, but reaction is already used → chain terminates.
-/
axiom hellish_rebuke_trigger
    (gs : GameState) (attacker target : EntityId) :
    (gs.getEntity target).isSome →
    (gs.getEntity target).get! |>.hasCondition (.custom "HellishRebukePrepared") →
    ¬ (gs.getEntity target).get!.reactionUsed →
    ∃ gs', step gs (.useReaction target "HellishRebuke"
      (.takeDamage attacker [⟨⟨2, 10, 0⟩, .fire⟩])) = some gs'

-- ═══════════════════════════════════════════════════════════════════════
-- P3: CONCENTRATION INVARIANT
-- ═══════════════════════════════════════════════════════════════════════

/--
**Concentration Rule**: Casting a concentration spell while already
concentrating on another must first break the existing concentration.

Formalized: after any `castSpell` event on a concentration spell,
the caster has at most one `concentratingOn` value.
-/
axiom concentration_uniqueness
    (gs : GameState) (caster : EntityId) (spell1 spell2 : String)
    (slotLevel : Nat) (target : SpellTarget) :
    (gs.getEntity caster).isSome →
    (gs.getEntity caster).get!.concentratingOn = some spell1 →
    -- After casting spell2 (concentration), spell1 is dropped
    ∀ gs', step gs (.castSpell caster spell2 slotLevel target) = some gs' →
    (gs'.getEntity caster).get!.concentratingOn ≠ some spell1

/--
**Haste Self-Cast Bug** (from bg3.wiki):
If a creature casts Haste on itself then casts another concentration
spell, it immediately becomes Lethargic AND the new spell ends.
This means both concentration effects are lost.
-/
axiom haste_self_cast_bug
    (gs : GameState) (caster : EntityId) (newSpell : String)
    (slotLevel : Nat) (target : SpellTarget) :
    (gs.getEntity caster).isSome →
    (gs.getEntity caster).get!.concentratingOn = some "Haste" →
    (gs.getEntity caster).get!.hasCondition .hastened →
    ∀ gs', step gs (.castSpell caster newSpell slotLevel target) = some gs' →
    (gs'.getEntity caster).get!.hasCondition .lethargic

-- ═══════════════════════════════════════════════════════════════════════
-- P4: ACTION ECONOMY BOUNDEDNESS
-- ═══════════════════════════════════════════════════════════════════════

/--
**Claim**: The maximum number of attacks in a single turn is bounded.

Normal: 1 Action (1-2 attacks with Extra Attack)
Haste:  +1 Action (1 attack in Honour Mode, 2 in normal)
Action Surge: +1 Action (1-2 attacks)
Max in normal mode: 2 + 2 + 2 = 6 attacks
Max in Honour mode: 2 + 1 + 2 = 5 attacks

With Thief's Fast Hands (bonus action attack): +1
With offhand dual wield: +1
Theoretical max: 8 attacks per turn in normal mode.
-/
def maxAttacksPerTurn (hasExtraAttack : Bool) (hasHaste : Bool)
    (hasActionSurge : Bool) (honourMode : Bool)
    (hasBonusAttack : Bool) (hasDualWield : Bool) : Nat :=
  let baseAttacks := if hasExtraAttack then 2 else 1
  let hasteAttacks := if hasHaste then (if honourMode then 1 else baseAttacks) else 0
  let surgeAttacks := if hasActionSurge then baseAttacks else 0
  let bonusAttacks := if hasBonusAttack then 1 else 0
  let offhandAttacks := if hasDualWield then 1 else 0
  baseAttacks + hasteAttacks + surgeAttacks + bonusAttacks + offhandAttacks

theorem action_economy_bounded :
    ∀ ea h as hm ba dw,
    maxAttacksPerTurn ea h as hm ba dw ≤ 8 := by
  intro ea h as hm ba dw
  simp [maxAttacksPerTurn]
  cases ea <;> cases h <;> cases as <;> cases hm <;> cases ba <;> cases dw <;> simp

-- ═══════════════════════════════════════════════════════════════════════
-- P5: STATUS EFFECT STACK CONSISTENCY
-- ═══════════════════════════════════════════════════════════════════════

/--
**Stack ID Rule**: Two conditions with the same stack ID cannot coexist.
When a new condition with the same stack ID is applied, the StackType
determines the outcome.

We verify that `addCondition` preserves uniqueness for `overwrite` and
`ignore` types, and that `additive` correctly sums durations.
-/
theorem overwrite_replaces (e : Entity) (c : ActiveCondition)
    (h_type : c.stackType = .overwrite) :
    let e' := e.addCondition c
    (e'.conditions.filter (fun x => x.tag == c.tag)).length ≤ 1 := by
  simp [Entity.addCondition, h_type]
  sorry -- requires list lemmas; mechanically provable

theorem ignore_preserves_existing (e : Entity) (c : ActiveCondition)
    (h_type : c.stackType = .ignore)
    (h_exists : e.hasCondition c.tag = true) :
    e.addCondition c = e := by
  simp [Entity.addCondition, h_type, h_exists]

-- ═══════════════════════════════════════════════════════════════════════
-- CONCRETE SPELL AXIOMS (seeded from wiki data)
-- ═══════════════════════════════════════════════════════════════════════

/-- Fireball: 8d6 Fire, DEX save for half, 18m range, 4m radius AoE -/
axiom fireball_damage (gs : GameState) (target : EntityId)
    (h_exists : (gs.getEntity target).isSome) :
    let dmg := DamageRoll.mk ⟨8, 6, 0⟩ .fire
    ∃ gs', step gs (.takeDamage target [dmg]) = some gs' ∧
    (gs'.getEntity target).get!.hp ≤ (gs.getEntity target).get!.hp

/-- Counterspell: Reaction, interrupt a spell being cast.
    Bug: BG3 uses Intelligence for the ability check instead of the
    caster's spellcasting ability.  This axiom states the dc formula
    BG3 *actually uses*, which differs from 5e RAW. -/
axiom counterspell_uses_intelligence
    (gs : GameState) (caster reactor : EntityId)
    (spellLevel : Nat) :
    (gs.getEntity reactor).isSome →
    spellLevel > 3 →
    let dc := 10 + spellLevel
    ∃ gs', step gs (.useReaction reactor "Counterspell"
      (.castSpell caster "Counterspell" 3 (.single reactor))) = some gs'

/-- Hex: 1d6 Necrotic per attack roll hit, concentration.
    Bug: Hex bonus damage is doubled on critical hits (should not be). -/
axiom hex_crit_bug
    (gs : GameState) (hexedTarget caster : EntityId) :
    (gs.getEntity hexedTarget).isSome →
    (gs.getEntity hexedTarget).get!.hasCondition .hexed →
    let normalHexDmg := DamageRoll.mk ⟨1, 6, 0⟩ .necrotic
    let critHexDmg   := DamageRoll.mk ⟨2, 6, 0⟩ .necrotic
    ∃ gs_n gs_c,
      step gs (.takeDamage hexedTarget [normalHexDmg]) = some gs_n ∧
      step gs (.takeDamage hexedTarget [critHexDmg])   = some gs_c

end VALOR.Rules
